C:\Users\ErwinL\AppData\Local\Programs\Python\Python39\lib\site-packages\rasa\core\tracker_store.py:1044: MovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base: DeclarativeMeta = declarative_base()
C:\Users\ErwinL\AppData\Local\Programs\Python\Python39\lib\site-packages\rasa\shared\utils\validation.py:134: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
C:\Users\ErwinL\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py:3117: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
C:\Users\ErwinL\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py:3117: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('ruamel')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
C:\Users\ErwinL\AppData\Local\Programs\Python\Python39\lib\site-packages\sanic_cors\extension.py:39: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  SANIC_VERSION = LooseVersion(sanic_version)
2025-09-08 09:37:53 [1;30mINFO    [0m [34mrasa_sdk.endpoint[0m  - Starting action endpoint server...
2025-09-08 09:37:53 [1;30mINFO    [0m [34mrasa_sdk.executor[0m  - Registered function for 'action_validar_problema'.
2025-09-08 09:37:53 [1;30mINFO    [0m [34mrasa_sdk.executor[0m  - Registered function for 'action_crear_ticket'.
2025-09-08 09:37:53 [1;30mINFO    [0m [34mrasa_sdk.executor[0m  - Registered function for 'action_consultar_estado'.
2025-09-08 09:37:53 [1;30mINFO    [0m [34mrasa_sdk.executor[0m  - Registered function for 'action_responder_faq'.
2025-09-08 09:37:53 [1;30mINFO    [0m [34mrasa_sdk.executor[0m  - Registered function for 'action_clasificar_problema'.
2025-09-08 09:37:53 [1;30mINFO    [0m [34mrasa_sdk.endpoint[0m  - Starting plugins...
2025-09-08 09:37:53 [1;30mINFO    [0m [34mrasa_sdk.endpoint[0m  - Action endpoint is up and running on http://0.0.0.0:5055
Unable to start server
Traceback (most recent call last):
  File "C:\Users\ErwinL\AppData\Local\Programs\Python\Python39\lib\site-packages\sanic\server\runners.py", line 133, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "C:\Users\ErwinL\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\ErwinL\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1506, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 10048] error while attempting to bind on address ('0.0.0.0', 5055): solo se permite un uso de cada dirección de socket (protocolo/dirección de red/puerto)
